### ISSUE TITLE
PUT Method not allowed (External SSL)

### ISSUE THREAD

**Issue by doug62** [ianisms/SmartThings.NETCoreWebHookSDK#10]
Config:  When I attempt to validate my app through smarthings hub I receive:

Sending HTTP request PUT https://api.smartthings.com/apps/<token>/confirm-registration?token=<token>

And then a MethodNotAllowed exception.

The odd thing about my config is that I use Traefik/Acme/LetsEncrypt to convert https->http for my app, I'm wondering if that is the issue - any tips/updates appreciated.

**Comment by ianisms** [comment]
Quite possible that Samsung has changed the spec since I last updated.  I have a smart app that is live without issue however, I think the confirm-reg would only be called during install.  Will check as soon as time permits.

**Comment by ianisms** [comment]
Samsung changed how WebHook based SmartApps are registered and is now using the CONFIRMATION api as opposed to the PING api.  I will make the updates as well as rev to .NET 5.  Will also take the opportunity to do some cleanup.  This will require a number of changes.  Stay tuned.

**Comment by ianisms** [comment]
Should be fixed in latest release

**Comment by doug62** [comment]
THANKS!  Will pull it in a few days.
